# Firefox over VNC
# Install vnc, xvfb in order to create a 'fake' display and firefox
#
# VERSION               0.3
FROM fedora:24
RUN dnf -y install x11vnc xvfb firefox
RUN mkdir ~/.vnc
RUN x11vnc -storepasswd 1234 ~/.vnc/passwd
RUN bash -c 'echo "firefox" >> /.bashrc'
EXPOSE 5900
CMD    ["x11vnc", "-forever", "-usepw", "-create"]


